import { useEffect,useState } from 'react';
import { Users, UserCheck, IndianRupee, UserPlus } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '../services/api';
import type { Dashboard as DashboardData } from '../types';

export default function Dashboard(){const [data,setData]=useState<DashboardData|null>(null);const [error,setError]=useState('');useEffect(()=>{api.get('/dashboard').then(r=>setData(r.data)).catch(()=>setError('Could not load dashboard.'))},[]);if(error)return <div className="alert error">{error}</div>;if(!data)return <div className="loading">Loading dashboard...</div>;
const cards=[['Total Employees',data.total,Users],['Active Employees',data.active,UserCheck],['Monthly Payroll',`₹${data.salary.toLocaleString('en-IN')}`,IndianRupee],['New Hires',data.hiredThisMonth,UserPlus]] as const;
return <div><div className="stats-grid">{cards.map(([title,value,Icon])=><div className="stat-card" key={title}><div><span>{title}</span><strong>{value}</strong></div><Icon size={26}/></div>)}</div><div className="grid-2"><div className="panel"><div className="panel-title"><h2>Hiring Trend</h2><span>Last 12 months</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.hiringTrend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count"/></BarChart></ResponsiveContainer></div></div><div className="panel"><div className="panel-title"><h2>Department Growth</h2></div><div className="simple-list">{data.departments.map(d=><div key={d.name}><span>{d.name}</span><b>{d.employeeCount}</b></div>)}</div></div></div><div className="panel attendance-summary"><div className="panel-title"><h2>Attendance — Last 30 Days</h2></div><div className="simple-list">{data.attendance.map(a=><div key={a.status}><span>{a.status}</span><b>{a.count}</b></div>)}</div></div></div>}
