import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { api } from '../services/api';
import type { Employee, Department } from '../types';

export default function Employees(){const [items,setItems]=useState<Employee[]>([]);const [departments,setDepartments]=useState<Department[]>([]);const [search,setSearch]=useState('');const [departmentId,setDepartmentId]=useState('');const [loading,setLoading]=useState(true);
const load=()=>{setLoading(true);api.get('/employees',{params:{search,departmentId:departmentId||undefined}}).then(r=>setItems(r.data)).finally(()=>setLoading(false));};useEffect(()=>{api.get('/departments').then(r=>setDepartments(r.data));},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[search,departmentId]);
const remove=async(id:number)=>{if(!confirm('Delete this employee?'))return;await api.delete(`/employees/${id}`);load();};
return <div><div className="page-head"><div><h2>Employees</h2><p>Manage employee records and salary data.</p></div><Link className="primary" to="/employees/new"><Plus size={18}/> Add Employee</Link></div><div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search name, code or email" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">All departments</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Code</th><th>Name</th><th>Department</th><th>Job Title</th><th>Salary</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Loading...</td></tr>:items.length===0?<tr><td colSpan={7}>No employees found.</td></tr>:items.map(e=><tr key={e.id}><td>{e.employeeCode}</td><td><strong>{e.firstName} {e.lastName}</strong><br/><small>{e.email}</small></td><td>{e.departmentName}</td><td>{e.jobTitle}</td><td>₹{e.salary.toLocaleString('en-IN')}</td><td><span className={`badge ${e.isActive?'success':'muted'}`}>{e.isActive?'Active':'Inactive'}</span></td><td><div className="actions"><Link to={`/employees/${e.id}/edit`}><Pencil size={16}/></Link><button onClick={()=>remove(e.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></div>}
