import { FormEvent,useEffect,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { api } from '../services/api';
import type { Department, Employee } from '../types';

type Form={employeeCode:string;firstName:string;lastName:string;email:string;phone:string;jobTitle:string;salary:string;joiningDate:string;departmentId:string;isActive:boolean};
const initial:Form={employeeCode:'',firstName:'',lastName:'',email:'',phone:'',jobTitle:'',salary:'',joiningDate:new Date().toISOString().slice(0,10),departmentId:'',isActive:true};
export default function EmployeeForm(){const {id}=useParams();const editing=Boolean(id);const [form,setForm]=useState<Form>(initial);const [departments,setDepartments]=useState<Department[]>([]);const [error,setError]=useState('');const navigate=useNavigate();
useEffect(()=>{api.get('/departments').then(r=>setDepartments(r.data));if(id)api.get(`/employees/${id}`).then(r=>{const e:Employee=r.data;setForm({employeeCode:e.employeeCode,firstName:e.firstName,lastName:e.lastName,email:e.email,phone:e.phone,jobTitle:e.jobTitle,salary:String(e.salary),joiningDate:e.joiningDate.slice(0,10),departmentId:String(e.departmentId),isActive:e.isActive})})},[id]);
const change=(key:keyof Form,value:any)=>setForm(f=>({...f,[key]:value}));const submit=async(e:FormEvent)=>{e.preventDefault();setError('');const payload={...form,salary:Number(form.salary),departmentId:Number(form.departmentId)};try{if(editing)await api.put(`/employees/${id}`,payload);else await api.post('/employees',payload);navigate('/employees')}catch(err:any){setError(err.response?.data?.message??'Could not save employee.')}};
return <div className="form-page"><div className="page-head"><div><h2>{editing?'Edit Employee':'Add Employee'}</h2><p>Use valid details. Email and employee code must be unique.</p></div><Link className="secondary" to="/employees">Back</Link></div>{error&&<div className="alert error">{error}</div>}<form className="panel form-grid" onSubmit={submit}><label>Employee Code<input value={form.employeeCode} onChange={e=>change('employeeCode',e.target.value)} required maxLength={30}/></label><label>First Name<input value={form.firstName} onChange={e=>change('firstName',e.target.value)} required/></label><label>Last Name<input value={form.lastName} onChange={e=>change('lastName',e.target.value)} required/></label><label>Email<input type="email" value={form.email} onChange={e=>change('email',e.target.value)} required/></label><label>Phone<input value={form.phone} onChange={e=>change('phone',e.target.value)} required/></label><label>Job Title<input value={form.jobTitle} onChange={e=>change('jobTitle',e.target.value)} required/></label><label>Salary<input type="number" min="0" step="0.01" value={form.salary} onChange={e=>change('salary',e.target.value)} required/></label><label>Joining Date<input type="date" value={form.joiningDate} onChange={e=>change('joiningDate',e.target.value)} required/></label><label>Department<select value={form.departmentId} onChange={e=>change('departmentId',e.target.value)} required><option value="">Select department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={form.isActive} onChange={e=>change('isActive',e.target.checked)}/> Active employee</label><div className="form-actions"><Link className="secondary" to="/employees">Cancel</Link><button className="primary">{editing?'Update':'Create'} Employee</button></div></form></div>}
