using ClosedXML.Excel;
using EmployeeManagement.Api.Data;
using EmployeeManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace EmployeeManagement.Api.Services;

public class ReportService(AppDbContext db)
{
    public async Task<byte[]> EmployeeExcelAsync()
    {
        var employees = await db.Employees.AsNoTracking().Include(e => e.Department).OrderBy(e => e.Id).ToListAsync();
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Employees");
        var headers = new[] { "Code", "Name", "Email", "Phone", "Job Title", "Department", "Salary", "Joining Date", "Active" };
        for (var i = 0; i < headers.Length; i++) sheet.Cell(1, i + 1).Value = headers[i];
        for (var r = 0; r < employees.Count; r++)
        {
            var e = employees[r]; var row = r + 2;
            sheet.Cell(row, 1).Value = e.EmployeeCode;
            sheet.Cell(row, 2).Value = $"{e.FirstName} {e.LastName}";
            sheet.Cell(row, 3).Value = e.Email;
            sheet.Cell(row, 4).Value = e.Phone;
            sheet.Cell(row, 5).Value = e.JobTitle;
            sheet.Cell(row, 6).Value = e.Department?.Name ?? "";
            sheet.Cell(row, 7).Value = (double)e.Salary;
            sheet.Cell(row, 8).Value = e.JoiningDate;
            sheet.Cell(row, 9).Value = e.IsActive ? "Yes" : "No";
        }
        sheet.Columns().AdjustToContents();
        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public async Task<byte[]> EmployeePdfAsync()
    {
        var employees = await db.Employees.AsNoTracking().Include(e => e.Department).OrderBy(e => e.Id).ToListAsync();
        QuestPDF.Settings.License = LicenseType.Community;
        return Document.Create(container => container.Page(page =>
        {
            page.Margin(30);
            page.Header().Text("Employee Directory").FontSize(20).Bold();
            page.Content().Table(table =>
            {
                table.ColumnsDefinition(columns => { for (var i = 0; i < 7; i++) columns.RelativeColumn(); });
                foreach (var h in new[] { "Code", "Name", "Email", "Job Title", "Department", "Salary", "Status" })
                    table.Cell().BorderBottom(1).Padding(4).Text(h).Bold();
                foreach (var e in employees)
                {
                    table.Cell().Padding(4).Text(e.EmployeeCode);
                    table.Cell().Padding(4).Text($"{e.FirstName} {e.LastName}");
                    table.Cell().Padding(4).Text(e.Email);
                    table.Cell().Padding(4).Text(e.JobTitle);
                    table.Cell().Padding(4).Text(e.Department?.Name ?? "-");
                    table.Cell().Padding(4).Text(e.Salary.ToString("C"));
                    table.Cell().Padding(4).Text(e.IsActive ? "Active" : "Inactive");
                }
            });
            page.Footer().AlignCenter().Text(x => x.Span("Generated by Employee Management System"));
        })).GeneratePdf();
    }

    public async Task<byte[]> AttendanceExcelAsync(DateOnly from, DateOnly to)
    {
        var records = await db.Attendances.AsNoTracking().Include(a => a.Employee)
            .Where(a => a.Date >= from && a.Date <= to).OrderBy(a => a.Date).ThenBy(a => a.Employee!.FirstName).ToListAsync();
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add("Attendance");
        var headers = new[] { "Date", "Employee", "Code", "Status", "Notes" };
        for (var i = 0; i < headers.Length; i++) sheet.Cell(1, i + 1).Value = headers[i];
        for (var r = 0; r < records.Count; r++)
        {
            var a = records[r]; var row = r + 2;
            sheet.Cell(row, 1).Value = a.Date.ToString("yyyy-MM-dd");
            sheet.Cell(row, 2).Value = $"{a.Employee?.FirstName} {a.Employee?.LastName}";
            sheet.Cell(row, 3).Value = a.Employee?.EmployeeCode;
            sheet.Cell(row, 4).Value = a.Status.ToString();
            sheet.Cell(row, 5).Value = a.Notes ?? "";
        }
        sheet.Columns().AdjustToContents();
        using var stream = new MemoryStream(); workbook.SaveAs(stream); return stream.ToArray();
    }
}
